### PR TITLE
Update vuebars

### PR DESCRIPTION
**Pull request by notiv-nt**
Also, you need to create [github pages](https://pages.github.com/)

https://peterlamar.github.io/vue-examples/vuebars

### CODE REVIEW

**Comment by notiv-nt** [comment]
https://notiv-nt.github.io/vue-examples/vuebars/

**Comment by peterlamar** [comment]
The javascript from the readme doesn't match the javascript in the index.html. Are your thoughts to change the index.html or was this a simplification?

**Comment by notiv-nt** [comment]
did not pay attention to it

**Comment by peterlamar** [comment]
Ok, gotcha. I won't read too much into it then. I still like the approach

**Pull request merged**
